-- MySQL Script generated by MySQL Workbench
-- Fri Jan 20 13:51:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GestBot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GestBot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestBot` DEFAULT CHARACTER SET utf8 ;
USE `GestBot` ;

-- -----------------------------------------------------
-- Table `GestBot`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestBot`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestBot`.`Server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestBot`.`Server` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serverId` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `serverId_UNIQUE` (`serverId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestBot`.`Wallpapers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestBot`.`Wallpapers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `level` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestBot`.`Profils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestBot`.`Profils` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profilId` INT NOT NULL,
  `xp` INT NOT NULL DEFAULT 0,
  `level` INT NOT NULL DEFAULT 1,
  `nameColor` VARCHAR(8) NOT NULL DEFAULT '0000FF',
  `barColor` VARCHAR(8) NOT NULL DEFAULT 'ADFF2F',
  `Wallpapers_id` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `profilId_UNIQUE` (`profilId` ASC) VISIBLE,
  INDEX `fk_Profils_Wallpapers_idx` (`Wallpapers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profils_Wallpapers`
    FOREIGN KEY (`Wallpapers_id`)
    REFERENCES `GestBot`.`Wallpapers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestBot`.`Profils_has_Wallpapers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestBot`.`Profils_has_Wallpapers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Profils_id` INT NOT NULL,
  `Wallpapers_id` INT NOT NULL,
  INDEX `fk_Profils_has_Wallpapers_Wallpapers1_idx` (`Wallpapers_id` ASC) VISIBLE,
  INDEX `fk_Profils_has_Wallpapers_Profils1_idx` (`Profils_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `Profils_Wallpapers_Unique` (`Profils_id` ASC, `Wallpapers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profils_has_Wallpapers_Profils1`
    FOREIGN KEY (`Profils_id`)
    REFERENCES `GestBot`.`Profils` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profils_has_Wallpapers_Wallpapers1`
    FOREIGN KEY (`Wallpapers_id`)
    REFERENCES `GestBot`.`Wallpapers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestBot`.`Server_has_Profils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestBot`.`Server_has_Profils` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Server_id` INT NOT NULL,
  `Profils_id` INT NOT NULL,
  INDEX `fk_Server_has_Profils_Profils1_idx` (`Profils_id` ASC) VISIBLE,
  INDEX `fk_Server_has_Profils_Server1_idx` (`Server_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Server_Profils_Unique` (`Server_id` ASC, `Profils_id` ASC) VISIBLE,
  CONSTRAINT `fk_Server_has_Profils_Server1`
    FOREIGN KEY (`Server_id`)
    REFERENCES `GestBot`.`Server` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Server_has_Profils_Profils1`
    FOREIGN KEY (`Profils_id`)
    REFERENCES `GestBot`.`Profils` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestBot`.`Users_makes_Profils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestBot`.`Users_makes_Profils` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Users_id` INT NOT NULL,
  `Profils_id` INT NOT NULL,
  INDEX `fk_Users_has_Profils_Profils1_idx` (`Profils_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Profils_Users1_idx` (`Users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Users_Profils_Unique` (`Profils_id` ASC, `Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Profils_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `GestBot`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Profils_Profils1`
    FOREIGN KEY (`Profils_id`)
    REFERENCES `GestBot`.`Profils` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
